### ISSUE TITLE
Unable to `import` and use a Python Module simultaneously in `do` form

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#1028]
Hi,

It seems that it's not possible to import and use a Python module within a do form simultaneously
```
unable to resolve symbol 'logging/getLogger' in this context
```

To reproduce, open a REPL and try importing and using the `logging` module within a `do` form
```clojure
basilisp.user=> (do (import logging) (logging/getLogger "abc"))

  exception: <class 'basilisp.lang.compiler.exception.CompilerException'>
      phase: :analyzing
    message: unable to resolve symbol 'logging/getLogger' in this context
       form: logging/getLogger
   location: <REPL Input>:1
```

However, the same code works as expected when not using the `do` form:
```clojure
basilisp.user=> (import logging) (logging/getLogger "abc")
<Logger abc (WARNING)>
```

I would expect this to work inside a `do` form as well. 

Thanks

**Comment by chrisrink10** [comment]
This is basically the `import` case of #545 which is known as the [Gilardi scenario](https://technomancy.us/143) (no idea where the name comes from).

Clojure seems to have special cased top-level `do`s to allow handling this, but I suspect that would be a tremendous amount of very hacky effort in Basilisp because of how the compiler is structured. I'd suggest using more dynamic lookup for now like what is suggested in the provided link.

**Comment by chrisrink10** [comment]
@ikappaki I'm about to merge #1061 which should fix the issue as you've described it in the ticket, but you'll have to let me know if it actually resolves the issue or if there was actually something else you were trying to do that my changeset doesn't cover.

**Comment by ikappaki** [comment]
> @ikappaki I'm about to merge #1061 which should fix the issue as you've described it in the ticket, but you'll have to let me know if it actually resolves the issue or if there was actually something else you were trying to do that my changeset doesn't cover.

Hi @chrisrink10, I can't recall the exact code since it has changed, but I believe it was something like this:

```clojure
(binding [*out* sys/stdout]
  (import logging)
  (logging/getLogger "abc"))
```

which expand to
```clojure
(do (basilisp.core/push-thread-bindings (basilisp.core/hash-map (var *out*) sys/stdout))
    (try (import logging)
         (logging/getLogger "abc")
         (finally (basilisp.core/pop-thread-bindings))))
```

At the time, I thought the issue was with the `do` form, which was reproducible and led to this issue being opened.

Now, the `do` form works with the latest changes (great job!):
```clojure
basilisp.user=> (do
                  (import logging)
                  (logging/getLogger "abc"))
<Logger abc (WARNING)>
```

However, the `try` form still fails, which was likely the original cause:
```clojure
basilisp.user=> (try
                  (import logging)
                  (logging/getLogger "abc")
                  (finally :done))

  exception: <class 'basilisp.lang.compiler.exception.CompilerException'>
      phase: :analyzing
    message: unable to resolve symbol 'logging/getLogger' in this context
       form: logging/getLogger
   location: <REPL Input>:3
```

Would you like me to open a new issue for the `try` failure?

Thanks

**Comment by chrisrink10** [comment]
Thanks for the additional context. I think we can open that issue although I'm not sure there's any easy solutions at the compiler level for this.

I wonder if I should consider adding something like `requiring-resolve` but for Python names to get around this issue.

**Comment by ikappaki** [comment]
> Thanks for the additional context. I think we can open that issue although I'm not sure there's any easy solutions at the compiler level for this.

Opened https://github.com/basilisp-lang/basilisp/issues/1065

> 
> I wonder if I should consider adding something like `requiring-resolve` but for Python names to get around this issue.

No experience with `requiring-resolve` yet :)
